name: Deploy

on:
  push:
    branches: 
      - 'main'

jobs:
  prepare:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{secrets.AWS_ROLE_TO_ASSUME}}
          aws-region: ${{secrets.AWS_REGION}}

      - name: Runtask - Download task definition
        id: task-def
        uses: aws-actions/amazon-ecs-render-task-definition@master
        with:
          task-definition-family: test-ecs-renderTaskDefinition
          container-name: test-ecs-render
          image: public.ecr.aws/docker/library/httpd:2.4
          
      - name: Temporarily save task def
        uses: actions/upload-artifact@v4
        with:
          name: task-def
          path: /home/runner/work/_temp/**
          retention-days: 1
    outputs:
      task-definition: ${{ steps.task-def.outputs.task-definition }}

  deploy:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: temp-files
          path: /home/runner/work/_temp
      - name: Service - Deploy service to Amazon ECS
        uses: guikcd/amazon-ecs-deploy-task-definition@propagate_tags_get_current_value
        #uses: aws-actions/amazon-ecs-deploy-task-definition@v2.2.0
        with:
          # task-definition: task-definition.json
          task-definition: ${{ needs.prepare.outputs.task-definition }}
          service: test-ecs-render
          cluster: test-ecs-renderCluster
          wait-for-service-stability: true
          enable-ecs-managed-tags: true

  deploy-propagate-from-service:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: temp-files
          path: /home/runner/work/_temp
      - name: Service - Deploy service to Amazon ECS propagate from created service
        uses: guikcd/amazon-ecs-deploy-task-definition@propagate_tags_get_current_value
        #uses: aws-actions/amazon-ecs-deploy-task-definition@v2.2.0
        with:
          # task-definition: task-definition.json
          task-definition: ${{ needs.prepare.outputs.task-definition }}
          service: test-ecs-render-propagateTagsCreatedService
          cluster: test-ecs-renderCluster
          wait-for-service-stability: true
          enable-ecs-managed-tags: true

  deploy-propagate-update-service:
    runs-on: ubuntu-latest
    needs: prepare
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: temp-files
          path: /home/runner/work/_temp
      - name: Service - Deploy service to Amazon ECS propagate update service
        uses: guikcd/amazon-ecs-deploy-task-definition@propagate_tags_get_current_value
        #uses: aws-actions/amazon-ecs-deploy-task-definition@v2.2.0
        with:
          # task-definition: task-definition.json
          task-definition: ${{ needs.prepare.outputs.task-definition }}
          service: test-ecs-render-propagateTagsUpdateService
          cluster: test-ecs-renderCluster
          wait-for-service-stability: true
          enable-ecs-managed-tags: true
          propagate-tags: SERVICE

      #- name: Check tags
      #  run: |
      #    #aws ecs describe-tasks --cluster test-ecs-deploy-task-definition-cluster --tasks $task --query 'tasks[?group==`service:test-ecs-deploy-task-definition-service`].taskArn' --output text
